#!/bin/python3

import math
import os
import random
import re
import sys


def stringConstruction(s):
    unique_list = []
    cost = 0
    for char in s:
        if char not in unique_list:
            unique_list.append(char)
            cost += 1
    return cost


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = stringConstruction(s)

        fptr.write(str(result) + '\n')

    fptr.close()
