#!/bin/python3

import math
import os
import random
import re
import sys


def quickSort(arr):
    center = arr[0]
    arr = sorted(arr)
    sorted_list = [center]
    for element in arr:
        if element < center:
            sorted_list.insert(0,element)
        elif element > center :
             sorted_list.insert(arr.index(element),element)
    return sorted_list

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = quickSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
